# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Enable the Puppet provisioner, with will look in manifests
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "site.pp"
    puppet.module_path = "modules"
  end

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"


  config.vm.provider :virtualbox do |vbox|
    # enable symlinks
    vbox.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    vbox.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/webroot", "1"]
    #vbox.gui = true # <- turn on GUI
  end

  # Forward guest port 80 to host port 8888 and name mapping
  config.vm.network :forwarded_port, guest: 80, host: 8080 #Apache/2.2.22 (Ubuntu)
  config.vm.network :forwarded_port, guest: 81, host: 8181 #nginx (Ubuntu)

  # shared folder
  config.vm.synced_folder "public/", "/vagrant/webroot/", :owner => "www-data"

end

